# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.2

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainWidget.setGeometry(QtCore.QRect(0, 10, 1101, 631))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mainWidget.setFont(font)
        self.mainWidget.setObjectName("mainWidget")
        self.log_in = QtWidgets.QWidget()
        self.log_in.setObjectName("log_in")
        self.buttonLogIn = QtWidgets.QPushButton(self.log_in)
        self.buttonLogIn.setGeometry(QtCore.QRect(410, 330, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonLogIn.setFont(font)
        self.buttonLogIn.setObjectName("buttonLogIn")
        self.label_28 = QtWidgets.QLabel(self.log_in)
        self.label_28.setGeometry(QtCore.QRect(320, 140, 441, 161))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_28.setFont(font)
        self.label_28.setLineWidth(1)
        self.label_28.setMidLineWidth(-7)
        self.label_28.setTextFormat(QtCore.Qt.PlainText)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setWordWrap(False)
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(self.log_in)
        self.label_30.setGeometry(QtCore.QRect(320, 450, 441, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setLineWidth(1)
        self.label_30.setMidLineWidth(-7)
        self.label_30.setTextFormat(QtCore.Qt.PlainText)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(False)
        self.label_30.setObjectName("label_30")
        self.mainWidget.addTab(self.log_in, "")
        self.get_emails = QtWidgets.QWidget()
        self.get_emails.setObjectName("get_emails")
        self.edit_lists = QtWidgets.QTabWidget(self.get_emails)
        self.edit_lists.setGeometry(QtCore.QRect(10, 50, 361, 371))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.edit_lists.setFont(font)
        self.edit_lists.setObjectName("edit_lists")
        self.add = QtWidgets.QWidget()
        self.add.setObjectName("add")
        self.addWord = QtWidgets.QPushButton(self.add)
        self.addWord.setGeometry(QtCore.QRect(90, 120, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addWord.setFont(font)
        self.addWord.setObjectName("addWord")
        self.editWord1 = QtWidgets.QLineEdit(self.add)
        self.editWord1.setGeometry(QtCore.QRect(90, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editWord1.setFont(font)
        self.editWord1.setText("")
        self.editWord1.setObjectName("editWord1")
        self.editWord1.setToolTip("example: word1, word2, etc...")
        self.editSection1 = QtWidgets.QLineEdit(self.add)
        self.editSection1.setGeometry(QtCore.QRect(90, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editSection1.setFont(font)
        self.editSection1.setText("")
        self.editSection1.setObjectName("editSection1")
        self.editSection1.setToolTip("name of the section in which words will be added")
        self.word1 = QtWidgets.QLabel(self.add)
        self.word1.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.word1.setFont(font)
        self.word1.setObjectName("word1")
        self.section1 = QtWidgets.QLabel(self.add)
        self.section1.setGeometry(QtCore.QRect(10, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.section1.setFont(font)
        self.section1.setObjectName("section1")
        self.editWord2 = QtWidgets.QLineEdit(self.add)
        self.editWord2.setGeometry(QtCore.QRect(90, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editWord2.setFont(font)
        self.editWord2.setText("")
        self.editWord2.setObjectName("editWord2")
        self.editWord2.setToolTip("example: word1, word2, etc...")
        self.section2 = QtWidgets.QLabel(self.add)
        self.section2.setGeometry(QtCore.QRect(10, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.section2.setFont(font)
        self.section2.setObjectName("section2")
        self.editSection2 = QtWidgets.QLineEdit(self.add)
        self.editSection2.setGeometry(QtCore.QRect(90, 240, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editSection2.setFont(font)
        self.editSection2.setText("")
        self.editSection2.setObjectName("editSection2")
        self.editSection2.setToolTip("name of the new section\nif such section already exists they will be added to it")
        self.word2 = QtWidgets.QLabel(self.add)
        self.word2.setGeometry(QtCore.QRect(10, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.word2.setFont(font)
        self.word2.setObjectName("word2")
        self.addSection = QtWidgets.QPushButton(self.add)
        self.addSection.setGeometry(QtCore.QRect(90, 290, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addSection.setFont(font)
        self.addSection.setObjectName("addSection")
        self.success1 = QtWidgets.QLabel(self.add)
        self.success1.setGeometry(QtCore.QRect(230, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.success1.setFont(font)
        self.success1.setText("")
        self.success1.setAlignment(QtCore.Qt.AlignCenter)
        self.success1.setObjectName("success1")
        self.success2 = QtWidgets.QLabel(self.add)
        self.success2.setGeometry(QtCore.QRect(230, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.success2.setFont(font)
        self.success2.setText("")
        self.success2.setAlignment(QtCore.Qt.AlignCenter)
        self.success2.setObjectName("success2")
        self.edit_lists.addTab(self.add, "")
        self.delete = QtWidgets.QWidget()
        self.delete.setObjectName("delete")
        self.section1_2 = QtWidgets.QLabel(self.delete)
        self.section1_2.setGeometry(QtCore.QRect(10, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.section1_2.setFont(font)
        self.section1_2.setObjectName("section1_2")
        self.section2_2 = QtWidgets.QLabel(self.delete)
        self.section2_2.setGeometry(QtCore.QRect(10, 190, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.section2_2.setFont(font)
        self.section2_2.setObjectName("section2_2")
        self.editSection2_2 = QtWidgets.QLineEdit(self.delete)
        self.editSection2_2.setGeometry(QtCore.QRect(90, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editSection2_2.setFont(font)
        self.editSection2_2.setText("")
        self.editSection2_2.setObjectName("editSection2_2")
        self.editSection2_2.setToolTip("name of the section that will be deleted")
        self.word1_2 = QtWidgets.QLabel(self.delete)
        self.word1_2.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.word1_2.setFont(font)
        self.word1_2.setObjectName("word1_2")
        self.editSection1_2 = QtWidgets.QLineEdit(self.delete)
        self.editSection1_2.setGeometry(QtCore.QRect(90, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editSection1_2.setFont(font)
        self.editSection1_2.setText("")
        self.editSection1_2.setObjectName("editSection1_2")
        self.editSection1_2.setToolTip("name of section where words will be deleted\nif none provided words will be deleted from all sections")
        self.deleteWord = QtWidgets.QPushButton(self.delete)
        self.deleteWord.setGeometry(QtCore.QRect(90, 120, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteWord.setFont(font)
        self.deleteWord.setObjectName("deleteWord")
        self.editWord1_2 = QtWidgets.QLineEdit(self.delete)
        self.editWord1_2.setGeometry(QtCore.QRect(90, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editWord1_2.setFont(font)
        self.editWord1_2.setText("")
        self.editWord1_2.setObjectName("editWord1_2")
        self.editWord1_2.setToolTip("example: word1, word2, etc...")
        self.deleteSection = QtWidgets.QPushButton(self.delete)
        self.deleteSection.setGeometry(QtCore.QRect(90, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deleteSection.setFont(font)
        self.deleteSection.setObjectName("deleteSection")
        self.success3 = QtWidgets.QLabel(self.delete)
        self.success3.setGeometry(QtCore.QRect(250, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.success3.setFont(font)
        self.success3.setText("")
        self.success3.setAlignment(QtCore.Qt.AlignCenter)
        self.success3.setObjectName("success3")
        self.success4 = QtWidgets.QLabel(self.delete)
        self.success4.setGeometry(QtCore.QRect(250, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.success4.setFont(font)
        self.success4.setText("")
        self.success4.setAlignment(QtCore.Qt.AlignCenter)
        self.success4.setObjectName("success4")
        self.edit_lists.addTab(self.delete, "")
        self.show = QtWidgets.QWidget()
        self.show.setObjectName("show")
        self.listSections = QtWidgets.QListWidget(self.show)
        self.listSections.setGeometry(QtCore.QRect(10, 20, 161, 231))
        self.listSections.setObjectName("listSections")
        self.showSections = QtWidgets.QPushButton(self.show)
        self.showSections.setGeometry(QtCore.QRect(90, 270, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.showSections.setFont(font)
        self.showSections.setObjectName("showSections")
        self.listWords = QtWidgets.QListWidget(self.show)
        self.listWords.setGeometry(QtCore.QRect(180, 20, 161, 231))
        self.listWords.setObjectName("listWords")
        self.edit_lists.addTab(self.show, "")
        self.label = QtWidgets.QLabel(self.get_emails)
        self.label.setGeometry(QtCore.QRect(10, 430, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.editPath = QtWidgets.QLineEdit(self.get_emails)
        self.editPath.setGeometry(QtCore.QRect(10, 500, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editPath.setFont(font)
        self.editPath.setText("")
        self.editPath.setObjectName("editPath")
        self.editPath.setToolTip("example: C:\\user\\emails\\")
        self.label_2 = QtWidgets.QLabel(self.get_emails)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.getAllEmails = QtWidgets.QPushButton(self.get_emails)
        self.getAllEmails.setGeometry(QtCore.QRect(410, 60, 191, 41))
        self.getAllEmails.setObjectName("getAllEmails")
        self.allEmailsFile = QtWidgets.QComboBox(self.get_emails)
        self.allEmailsFile.setGeometry(QtCore.QRect(410, 110, 191, 31))
        self.allEmailsFile.setObjectName("allEmailsFile")
        self.allEmailsFile.addItem("")
        self.allEmailsFile.addItem("")
        self.allEmailsFile.setToolTip("type of the output file")
        self.label_3 = QtWidgets.QLabel(self.get_emails)
        self.label_3.setGeometry(QtCore.QRect(400, 10, 661, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.getUrgentEmails = QtWidgets.QPushButton(self.get_emails)
        self.getUrgentEmails.setGeometry(QtCore.QRect(640, 60, 191, 41))
        self.getUrgentEmails.setObjectName("getUrgentEmails")
        self.urgentEmailsFile = QtWidgets.QComboBox(self.get_emails)
        self.urgentEmailsFile.setGeometry(QtCore.QRect(640, 110, 191, 31))
        self.urgentEmailsFile.setObjectName("urgentEmailsFile")
        self.urgentEmailsFile.addItem("")
        self.urgentEmailsFile.addItem("")
        self.urgentEmailsFile.setToolTip("type of the output file")
        self.getKeywordEmails = QtWidgets.QPushButton(self.get_emails)
        self.getKeywordEmails.setGeometry(QtCore.QRect(870, 60, 191, 41))
        self.getKeywordEmails.setObjectName("getKeywordEmails")
        self.keywordEmailsFile = QtWidgets.QComboBox(self.get_emails)
        self.keywordEmailsFile.setGeometry(QtCore.QRect(870, 110, 191, 31))
        self.keywordEmailsFile.setObjectName("keywordEmailsFile")
        self.keywordEmailsFile.addItem("")
        self.keywordEmailsFile.addItem("")
        self.keywordEmailsFile.setToolTip("type of the output file")
        self.keywordName = QtWidgets.QLineEdit(self.get_emails)
        self.keywordName.setGeometry(QtCore.QRect(870, 150, 191, 31))
        self.keywordName.setText("")
        self.keywordName.setObjectName("keywordName")
        self.label_4 = QtWidgets.QLabel(self.get_emails)
        self.label_4.setGeometry(QtCore.QRect(870, 180, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.get_emails)
        self.label_5.setGeometry(QtCore.QRect(400, 430, 661, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.editAfter = QtWidgets.QLineEdit(self.get_emails)
        self.editAfter.setGeometry(QtCore.QRect(590, 270, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editAfter.setFont(font)
        self.editAfter.setText("")
        self.editAfter.setObjectName("editAfter")
        self.editAfter.setToolTip("example: 2014/02/01 (yyyy/mm/dd)")
        self.label_6 = QtWidgets.QLabel(self.get_emails)
        self.label_6.setGeometry(QtCore.QRect(410, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.get_emails)
        self.label_7.setGeometry(QtCore.QRect(410, 270, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.editBefore = QtWidgets.QLineEdit(self.get_emails)
        self.editBefore.setGeometry(QtCore.QRect(590, 310, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editBefore.setFont(font)
        self.editBefore.setText("")
        self.editBefore.setObjectName("editBefore")
        self.editBefore.setToolTip("example: 2015/02/01 (yyyy/mm/dd)")
        self.label_8 = QtWidgets.QLabel(self.get_emails)
        self.label_8.setGeometry(QtCore.QRect(410, 310, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.editUnread = QtWidgets.QLineEdit(self.get_emails)
        self.editUnread.setGeometry(QtCore.QRect(590, 350, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editUnread.setFont(font)
        self.editUnread.setText("")
        self.editUnread.setObjectName("editUnread")
        self.editUnread.setToolTip("write \"read\" or \"unread\"\nby default will use all emails")
        self.label_9 = QtWidgets.QLabel(self.get_emails)
        self.label_9.setGeometry(QtCore.QRect(410, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.get_emails)
        self.label_10.setGeometry(QtCore.QRect(410, 390, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.editFrom = QtWidgets.QLineEdit(self.get_emails)
        self.editFrom.setGeometry(QtCore.QRect(590, 390, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editFrom.setFont(font)
        self.editFrom.setText("")
        self.editFrom.setObjectName("editFrom")
        self.editFrom.setToolTip("example: user@gmail.com")
        self.label_11 = QtWidgets.QLabel(self.get_emails)
        self.label_11.setGeometry(QtCore.QRect(410, 510, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.messageID = QtWidgets.QLineEdit(self.get_emails)
        self.messageID.setGeometry(QtCore.QRect(410, 480, 161, 31))
        self.messageID.setText("")
        self.messageID.setObjectName("messageID")
        self.messageID.setToolTip("ID of the message where attachment is")
        self.label_12 = QtWidgets.QLabel(self.get_emails)
        self.label_12.setGeometry(QtCore.QRect(580, 510, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.attachmentID = QtWidgets.QLineEdit(self.get_emails)
        self.attachmentID.setGeometry(QtCore.QRect(580, 480, 161, 31))
        self.attachmentID.setText("")
        self.attachmentID.setObjectName("attachmentID")
        self.attachmentID.setToolTip("ID of the attachment that must be downloaded\nIf none provided will download all attachments")
        self.pathForAttachment = QtWidgets.QLineEdit(self.get_emails)
        self.pathForAttachment.setGeometry(QtCore.QRect(750, 480, 161, 31))
        self.pathForAttachment.setText("")
        self.pathForAttachment.setObjectName("pathForAttachment")
        self.pathForAttachment.setToolTip("example: C:\\user\\emails\\")
        self.attachmentName = QtWidgets.QLineEdit(self.get_emails)
        self.attachmentName.setGeometry(QtCore.QRect(920, 480, 161, 31))
        self.attachmentName.setText("")
        self.attachmentName.setObjectName("attachmentName")
        self.attachmentName.setToolTip("full name for downloaded attachment (if there's more than one)\nexample: test.jpg")
        self.label_13 = QtWidgets.QLabel(self.get_emails)
        self.label_13.setGeometry(QtCore.QRect(750, 510, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.get_emails)
        self.label_14.setGeometry(QtCore.QRect(920, 510, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.downloadAttchment = QtWidgets.QPushButton(self.get_emails)
        self.downloadAttchment.setGeometry(QtCore.QRect(650, 540, 191, 41))
        self.downloadAttchment.setObjectName("downloadAttchment")
        self.keywordFileName = QtWidgets.QLineEdit(self.get_emails)
        self.keywordFileName.setGeometry(QtCore.QRect(870, 200, 191, 31))
        self.keywordFileName.setText("")
        self.keywordFileName.setObjectName("keywordFileName")
        self.keywordFileName.setToolTip("name of the file\nby default keyword section's name")
        self.label_29 = QtWidgets.QLabel(self.get_emails)
        self.label_29.setGeometry(QtCore.QRect(870, 230, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.success5 = QtWidgets.QLabel(self.get_emails)
        self.success5.setGeometry(QtCore.QRect(410, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.success5.setFont(font)
        self.success5.setText("")
        self.success5.setTextFormat(QtCore.Qt.AutoText)
        self.success5.setScaledContents(False)
        self.success5.setAlignment(QtCore.Qt.AlignCenter)
        self.success5.setWordWrap(True)
        self.success5.setObjectName("success5")
        self.success6 = QtWidgets.QLabel(self.get_emails)
        self.success6.setGeometry(QtCore.QRect(640, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.success6.setFont(font)
        self.success6.setText("")
        self.success6.setTextFormat(QtCore.Qt.AutoText)
        self.success6.setScaledContents(False)
        self.success6.setAlignment(QtCore.Qt.AlignCenter)
        self.success6.setWordWrap(True)
        self.success6.setObjectName("success6")
        self.success7 = QtWidgets.QLabel(self.get_emails)
        self.success7.setGeometry(QtCore.QRect(870, 250, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.success7.setFont(font)
        self.success7.setText("")
        self.success7.setTextFormat(QtCore.Qt.AutoText)
        self.success7.setScaledContents(False)
        self.success7.setAlignment(QtCore.Qt.AlignCenter)
        self.success7.setWordWrap(True)
        self.success7.setObjectName("success7")
        self.success8 = QtWidgets.QLabel(self.get_emails)
        self.success8.setGeometry(QtCore.QRect(870, 540, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.success8.setFont(font)
        self.success8.setText("")
        self.success8.setTextFormat(QtCore.Qt.AutoText)
        self.success8.setScaledContents(False)
        self.success8.setAlignment(QtCore.Qt.AlignCenter)
        self.success8.setWordWrap(True)
        self.success8.setObjectName("success8")
        self.label_32 = QtWidgets.QLabel(self.get_emails)
        self.label_32.setGeometry(QtCore.QRect(410, 180, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.allEmailsFileName = QtWidgets.QLineEdit(self.get_emails)
        self.allEmailsFileName.setGeometry(QtCore.QRect(410, 150, 191, 31))
        self.allEmailsFileName.setText("")
        self.allEmailsFileName.setObjectName("allEmailsFileName")
        self.allEmailsFileName.setToolTip("name of the file\nby default \"all_emails\"")
        self.label_33 = QtWidgets.QLabel(self.get_emails)
        self.label_33.setGeometry(QtCore.QRect(640, 180, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.urgentFileName = QtWidgets.QLineEdit(self.get_emails)
        self.urgentFileName.setGeometry(QtCore.QRect(640, 150, 191, 31))
        self.urgentFileName.setText("")
        self.urgentFileName.setObjectName("urgentFileName")
        self.urgentFileName.setToolTip("name of the file\nby default \"urgent_messages\"")
        self.mainWidget.addTab(self.get_emails, "")
        self.download = QtWidgets.QWidget()
        self.download.setObjectName("download")
        self.listWidget = QtWidgets.QListWidget(self.download)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 256, 351))
        self.listWidget.setObjectName("listWidget")
        self.label_34 = QtWidgets.QLabel(self.download)
        self.label_34.setGeometry(QtCore.QRect(20, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setTextFormat(QtCore.Qt.AutoText)
        self.label_34.setScaledContents(False)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.listWidget_2 = QtWidgets.QListWidget(self.download)
        self.listWidget_2.setGeometry(QtCore.QRect(300, 60, 781, 351))
        self.listWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_35 = QtWidgets.QLabel(self.download)
        self.label_35.setGeometry(QtCore.QRect(560, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setTextFormat(QtCore.Qt.AutoText)
        self.label_35.setScaledContents(False)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.getAllEmails_2 = QtWidgets.QPushButton(self.download)
        self.getAllEmails_2.setGeometry(QtCore.QRect(300, 420, 151, 41))
        self.getAllEmails_2.setObjectName("getAllEmails_2")
        self.keywordName_2 = QtWidgets.QLineEdit(self.download)
        self.keywordName_2.setGeometry(QtCore.QRect(460, 470, 171, 31))
        self.keywordName_2.setText("")
        self.keywordName_2.setObjectName("keywordName_2")
        self.getKeywordEmails_2 = QtWidgets.QPushButton(self.download)
        self.getKeywordEmails_2.setGeometry(QtCore.QRect(460, 420, 171, 41))
        self.getKeywordEmails_2.setObjectName("getKeywordEmails_2")
        self.label_36 = QtWidgets.QLabel(self.download)
        self.label_36.setGeometry(QtCore.QRect(460, 500, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.download)
        self.label_37.setGeometry(QtCore.QRect(650, 520, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.editFrom_2 = QtWidgets.QLineEdit(self.download)
        self.editFrom_2.setGeometry(QtCore.QRect(830, 560, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editFrom_2.setFont(font)
        self.editFrom_2.setText("")
        self.editFrom_2.setToolTip("example: user@gmail.com")
        self.editFrom_2.setObjectName("editFrom_2")
        self.editBefore_2 = QtWidgets.QLineEdit(self.download)
        self.editBefore_2.setGeometry(QtCore.QRect(830, 480, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editBefore_2.setFont(font)
        self.editBefore_2.setText("")
        self.editBefore_2.setToolTip("example: 2015/02/01 (yyyy/mm/dd)")
        self.editBefore_2.setObjectName("editBefore_2")
        self.editUnread_2 = QtWidgets.QLineEdit(self.download)
        self.editUnread_2.setGeometry(QtCore.QRect(830, 520, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editUnread_2.setFont(font)
        self.editUnread_2.setText("")
        self.editUnread_2.setToolTip("write \"read\" or \"unread\"\nby default will use all emails")
        self.editUnread_2.setObjectName("editUnread_2")
        self.label_38 = QtWidgets.QLabel(self.download)
        self.label_38.setGeometry(QtCore.QRect(650, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.download)
        self.label_39.setGeometry(QtCore.QRect(650, 410, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.download)
        self.label_40.setGeometry(QtCore.QRect(650, 440, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.editAfter_2 = QtWidgets.QLineEdit(self.download)
        self.editAfter_2.setGeometry(QtCore.QRect(830, 440, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editAfter_2.setFont(font)
        self.editAfter_2.setText("")
        self.editAfter_2.setToolTip("example: 2014/02/01 (yyyy/mm/dd)")
        self.editAfter_2.setObjectName("editAfter_2")
        self.label_41 = QtWidgets.QLabel(self.download)
        self.label_41.setGeometry(QtCore.QRect(650, 480, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.downloadAttchment_2 = QtWidgets.QPushButton(self.download)
        self.downloadAttchment_2.setGeometry(QtCore.QRect(20, 420, 256, 41))
        self.downloadAttchment_2.setToolTip("choose emails to download their attachments\nyou can change path for them")
        self.downloadAttchment_2.setObjectName("downloadAttchment_2")
        self.pathForAttachment_3 = QtWidgets.QLineEdit(self.download)
        self.pathForAttachment_3.setGeometry(QtCore.QRect(20, 480, 256, 31))
        self.pathForAttachment_3.setText("")
        self.pathForAttachment_3.setToolTip("example: C:\\user\\emails\\")
        self.pathForAttachment_3.setObjectName("pathForAttachment_3")
        self.label_82 = QtWidgets.QLabel(self.download)
        self.label_82.setGeometry(QtCore.QRect(20, 510, 256, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_82.setFont(font)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.editFileType_2 = QtWidgets.QLineEdit(self.download)
        self.editFileType_2.setGeometry(QtCore.QRect(20, 530, 256, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editFileType_2.setFont(font)
        self.editFileType_2.setText("")
        self.editFileType_2.setToolTip("if you want to download only one type of files\nfor example: .pdf")
        self.editFileType_2.setObjectName("editFileType_2")
        self.label_83 = QtWidgets.QLabel(self.download)
        self.label_83.setGeometry(QtCore.QRect(20, 560, 256, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_83.setFont(font)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.mainWidget.addTab(self.download, "")
        self.check_works = QtWidgets.QWidget()
        self.check_works.setObjectName("check_works")
        self.label_15 = QtWidgets.QLabel(self.check_works)
        self.label_15.setGeometry(QtCore.QRect(590, 430, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.check_works)
        self.label_16.setGeometry(QtCore.QRect(730, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.check_works)
        self.label_17.setGeometry(QtCore.QRect(590, 350, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.editAfterCheck = QtWidgets.QLineEdit(self.check_works)
        self.editAfterCheck.setGeometry(QtCore.QRect(770, 310, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editAfterCheck.setFont(font)
        self.editAfterCheck.setText("")
        self.editAfterCheck.setObjectName("editAfterCheck")
        self.editAfterCheck.setToolTip("example: 2014/02/01 (yyyy/mm/dd)")
        self.label_18 = QtWidgets.QLabel(self.check_works)
        self.label_18.setGeometry(QtCore.QRect(590, 390, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.editUnreadCheck = QtWidgets.QLineEdit(self.check_works)
        self.editUnreadCheck.setGeometry(QtCore.QRect(770, 390, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editUnreadCheck.setFont(font)
        self.editUnreadCheck.setText("")
        self.editUnreadCheck.setObjectName("editUnreadCheck")
        self.editUnreadCheck.setToolTip("write \"read\" or \"unread\"\nby default will use all emails")
        self.editFromCheck = QtWidgets.QLineEdit(self.check_works)
        self.editFromCheck.setGeometry(QtCore.QRect(770, 430, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editFromCheck.setFont(font)
        self.editFromCheck.setText("")
        self.editFromCheck.setObjectName("editFromCheck")
        self.editFromCheck.setToolTip("example: user@gmail.com")
        self.label_19 = QtWidgets.QLabel(self.check_works)
        self.label_19.setGeometry(QtCore.QRect(590, 310, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.editBeforeCheck = QtWidgets.QLineEdit(self.check_works)
        self.editBeforeCheck.setGeometry(QtCore.QRect(770, 350, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editBeforeCheck.setFont(font)
        self.editBeforeCheck.setText("")
        self.editBeforeCheck.setObjectName("editBeforeCheck")
        self.editBeforeCheck.setToolTip("example: 2015/02/01 (yyyy/mm/dd)")
        self.label_20 = QtWidgets.QLabel(self.check_works)
        self.label_20.setGeometry(QtCore.QRect(40, 30, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.check_works)
        self.label_21.setGeometry(QtCore.QRect(600, 30, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.editLabsFilename = QtWidgets.QLineEdit(self.check_works)
        self.editLabsFilename.setGeometry(QtCore.QRect(250, 150, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editLabsFilename.setFont(font)
        self.editLabsFilename.setText("")
        self.editLabsFilename.setObjectName("editLabsFilename")
        self.editLabsFilename.setToolTip("name for the file with results")
        self.label_22 = QtWidgets.QLabel(self.check_works)
        self.label_22.setGeometry(QtCore.QRect(70, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.editNumberLabs = QtWidgets.QLineEdit(self.check_works)
        self.editNumberLabs.setGeometry(QtCore.QRect(250, 110, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editNumberLabs.setFont(font)
        self.editNumberLabs.setText("")
        self.editNumberLabs.setObjectName("editNumberLabs")
        self.editNumberLabs.setToolTip("number of the labs\nfiles with labs must be named like\"lab_1\"")
        self.label_23 = QtWidgets.QLabel(self.check_works)
        self.label_23.setGeometry(QtCore.QRect(70, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.editPathCheck = QtWidgets.QLineEdit(self.check_works)
        self.editPathCheck.setGeometry(QtCore.QRect(90, 380, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editPathCheck.setFont(font)
        self.editPathCheck.setText("")
        self.editPathCheck.setObjectName("editPathCheck")
        self.editPathCheck.setToolTip("example: C:\\user\\emails\\")
        self.label_24 = QtWidgets.QLabel(self.check_works)
        self.label_24.setGeometry(QtCore.QRect(90, 310, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setScaledContents(False)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.editGroupNumber = QtWidgets.QLineEdit(self.check_works)
        self.editGroupNumber.setGeometry(QtCore.QRect(780, 110, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editGroupNumber.setFont(font)
        self.editGroupNumber.setText("")
        self.editGroupNumber.setObjectName("editGroupNumber")
        self.editGroupNumber.setToolTip("number of the group that must be present in email's text or subject")
        self.label_25 = QtWidgets.QLabel(self.check_works)
        self.label_25.setGeometry(QtCore.QRect(600, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.editProjectsFilename = QtWidgets.QLineEdit(self.check_works)
        self.editProjectsFilename.setGeometry(QtCore.QRect(780, 150, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editProjectsFilename.setFont(font)
        self.editProjectsFilename.setText("")
        self.editProjectsFilename.setObjectName("editProjectsFilename")
        self.editProjectsFilename.setToolTip("name for the file with results")
        self.label_26 = QtWidgets.QLabel(self.check_works)
        self.label_26.setGeometry(QtCore.QRect(600, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.editProjectsType = QtWidgets.QLineEdit(self.check_works)
        self.editProjectsType.setGeometry(QtCore.QRect(780, 190, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editProjectsType.setFont(font)
        self.editProjectsType.setText("")
        self.editProjectsType.setObjectName("editProjectsType")
        self.editProjectsType.setToolTip("needed type for attachments' files")
        self.label_27 = QtWidgets.QLabel(self.check_works)
        self.label_27.setGeometry(QtCore.QRect(600, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.checkLabs = QtWidgets.QPushButton(self.check_works)
        self.checkLabs.setGeometry(QtCore.QRect(160, 510, 221, 41))
        self.checkLabs.setObjectName("checkLabs")
        self.checkProjects = QtWidgets.QPushButton(self.check_works)
        self.checkProjects.setGeometry(QtCore.QRect(700, 510, 221, 41))
        self.checkProjects.setObjectName("checkProjects")
        self.success9 = QtWidgets.QLabel(self.check_works)
        self.success9.setGeometry(QtCore.QRect(180, 540, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.success9.setFont(font)
        self.success9.setText("")
        self.success9.setTextFormat(QtCore.Qt.AutoText)
        self.success9.setScaledContents(False)
        self.success9.setAlignment(QtCore.Qt.AlignCenter)
        self.success9.setWordWrap(True)
        self.success9.setObjectName("success9")
        self.success10 = QtWidgets.QLabel(self.check_works)
        self.success10.setGeometry(QtCore.QRect(720, 540, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.success10.setFont(font)
        self.success10.setText("")
        self.success10.setTextFormat(QtCore.Qt.AutoText)
        self.success10.setScaledContents(False)
        self.success10.setAlignment(QtCore.Qt.AlignCenter)
        self.success10.setWordWrap(True)
        self.success10.setObjectName("success10")
        self.mainWidget.addTab(self.check_works, "")
        self.logOut = QtWidgets.QPushButton(self.centralwidget)
        self.logOut.setGeometry(QtCore.QRect(940, 650, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logOut.setFont(font)
        self.logOut.setObjectName("logOut")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(520, 650, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setLineWidth(1)
        self.label_31.setMidLineWidth(-7)
        self.label_31.setText("")
        self.label_31.setTextFormat(QtCore.Qt.PlainText)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setWordWrap(False)
        self.label_31.setObjectName("label_31")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainWidget.setCurrentIndex(0)
        self.edit_lists.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gmail Helper"))
        self.buttonLogIn.setText(_translate("MainWindow", "Log in"))
        self.label_28.setText(_translate("MainWindow", "Welcome!\n"
"Please, log in for\n"
"further work"))
        self.label_30.setText(_translate("MainWindow", "You haven\'t logged in yet\n"
"You cannot process further"))
        self.mainWidget.setTabText(self.mainWidget.indexOf(self.log_in), _translate("MainWindow", "Log In"))
        self.addWord.setText(_translate("MainWindow", "Add word"))
        self.word1.setText(_translate("MainWindow", "Word(s)"))
        self.section1.setText(_translate("MainWindow", "Section"))
        self.section2.setText(_translate("MainWindow", "Section"))
        self.word2.setText(_translate("MainWindow", "Word(s)"))
        self.addSection.setText(_translate("MainWindow", "Add section"))
        self.edit_lists.setTabText(self.edit_lists.indexOf(self.add), _translate("MainWindow", "Add"))
        self.section1_2.setText(_translate("MainWindow", "Section"))
        self.section2_2.setText(_translate("MainWindow", "Section"))
        self.word1_2.setText(_translate("MainWindow", "Word(s)"))
        self.deleteWord.setText(_translate("MainWindow", "Delete word"))
        self.deleteSection.setText(_translate("MainWindow", "Delete section"))
        self.edit_lists.setTabText(self.edit_lists.indexOf(self.delete), _translate("MainWindow", "Delete"))
        self.showSections.setText(_translate("MainWindow", "Show sections"))
        self.edit_lists.setTabText(self.edit_lists.indexOf(self.show), _translate("MainWindow", "Show Existed"))
        self.label.setText(_translate("MainWindow", "Choose a path for files with emails (by default: program\'s folder)"))
        self.label_2.setText(_translate("MainWindow", "Edit keywords sections"))
        self.getAllEmails.setText(_translate("MainWindow", "Print all emails"))
        self.allEmailsFile.setItemText(0, _translate("MainWindow", ".json"))
        self.allEmailsFile.setItemText(1, _translate("MainWindow", ".txt"))
        self.label_3.setText(_translate("MainWindow", "Print emails into file"))
        self.getUrgentEmails.setText(_translate("MainWindow", "Print urgent emails"))
        self.urgentEmailsFile.setItemText(0, _translate("MainWindow", ".json"))
        self.urgentEmailsFile.setItemText(1, _translate("MainWindow", ".txt"))
        self.getKeywordEmails.setText(_translate("MainWindow", "Print keyword emails"))
        self.keywordEmailsFile.setItemText(0, _translate("MainWindow", ".json"))
        self.keywordEmailsFile.setItemText(1, _translate("MainWindow", ".txt"))
        self.label_4.setText(_translate("MainWindow", "keyword section"))
        self.label_5.setText(_translate("MainWindow", "Donwload atachment"))
        self.label_6.setText(_translate("MainWindow", "Optional parameters:"))
        self.label_7.setText(_translate("MainWindow", "After:"))
        self.label_8.setText(_translate("MainWindow", "Before:"))
        self.label_9.setText(_translate("MainWindow", "Read/Unread:"))
        self.label_10.setText(_translate("MainWindow", "From:"))
        self.label_11.setText(_translate("MainWindow", "message ID"))
        self.label_12.setText(_translate("MainWindow", "attachment ID"))
        self.label_13.setText(_translate("MainWindow", "path"))
        self.label_14.setText(_translate("MainWindow", "filename"))
        self.downloadAttchment.setText(_translate("MainWindow", "Download"))
        self.label_29.setText(_translate("MainWindow", "file name"))
        self.label_32.setText(_translate("MainWindow", "file name"))
        self.label_33.setText(_translate("MainWindow", "file name"))
        self.mainWidget.setTabText(self.mainWidget.indexOf(self.get_emails), _translate("MainWindow", "Emails to file"))
        self.label_34.setText(_translate("MainWindow", "Emails\' IDs"))
        self.label_35.setText(_translate("MainWindow", "Email\'s text"))
        self.getAllEmails_2.setText(_translate("MainWindow", "Print all emails"))
        self.getKeywordEmails_2.setText(_translate("MainWindow", "Print keyword emails"))
        self.label_36.setText(_translate("MainWindow", "keyword section"))
        self.label_37.setText(_translate("MainWindow", "Read/Unread:"))
        self.label_38.setText(_translate("MainWindow", "From:"))
        self.label_39.setText(_translate("MainWindow", "Optional parameters:"))
        self.label_40.setText(_translate("MainWindow", "After:"))
        self.label_41.setText(_translate("MainWindow", "Before:"))
        self.downloadAttchment_2.setText(_translate("MainWindow", "Download attachments"))
        self.label_82.setText(_translate("MainWindow", "path"))
        self.label_83.setText(_translate("MainWindow", "file\'s type"))
        self.mainWidget.setTabText(self.mainWidget.indexOf(self.download), _translate("MainWindow", "Show emails"))
        self.label_15.setText(_translate("MainWindow", "From:"))
        self.label_16.setText(_translate("MainWindow", "Optional parameters:"))
        self.label_17.setText(_translate("MainWindow", "Before:"))
        self.label_18.setText(_translate("MainWindow", "Read/Unread:"))
        self.label_19.setText(_translate("MainWindow", "After:"))
        self.label_20.setText(_translate("MainWindow", "Check labs"))
        self.label_21.setText(_translate("MainWindow", "Check course projects"))
        self.label_22.setText(_translate("MainWindow", "Number of labs:"))
        self.label_23.setText(_translate("MainWindow", "Filename:"))
        self.label_24.setText(_translate("MainWindow", "Choose a path for files with statistics (by default: program\'s folder)"))
        self.label_25.setText(_translate("MainWindow", "Group number:"))
        self.label_26.setText(_translate("MainWindow", "Filename:"))
        self.label_27.setText(_translate("MainWindow", "File\'s type:"))
        self.checkLabs.setText(_translate("MainWindow", "Check labs"))
        self.checkProjects.setText(_translate("MainWindow", "Check course projects"))
        self.mainWidget.setTabText(self.mainWidget.indexOf(self.check_works), _translate("MainWindow", "Check files"))
        self.logOut.setText(_translate("MainWindow", "Log Out"))
